<a href="https://colab.research.google.com/github/Sayaliravindrapatil/Bike-rental--OOPS-based/blob/main/Sentimental_Analysis_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)

In [ ]:
df_=pd.read_csv("/content/dataset[1].csv",nrows=2000)

In [ ]:
df_.head()

                                                Text Language      Label
0  @Charlie_Corley @Kristine1G @amyklobuchar @Sty...       en  litigious
1  #BadBunny: Como dos gotas de agua: Joven se di...       es   negative
2  https://t.co/YJNiO0p1JV Flagstar Bank disclose...       en  litigious
3  Rwanda is set to host the headquarters of Unit...       en   positive
4  OOPS. I typed her name incorrectly (today’s br...       en  litigious

In [ ]:
features=df_["Text"]
labels=df_["Label"]
df_.head()

                                                Text Language      Label
0  @Charlie_Corley @Kristine1G @amyklobuchar @Sty...       en  litigious
1  #BadBunny: Como dos gotas de agua: Joven se di...       es   negative
2  https://t.co/YJNiO0p1JV Flagstar Bank disclose...       en  litigious
3  Rwanda is set to host the headquarters of Unit...       en   positive
4  OOPS. I typed her name incorrectly (today’s br...       en  litigious

# **Conerting tweets to string datatype**

In [ ]:
df_["Text"]=df_["Text"].astype(str)

# **Converting to lower case features**

In [ ]:
features=(features.str.lower())
features

0       @charlie_corley @kristine1g @amyklobuchar @sty...
1       #badbunny: como dos gotas de agua: joven se di...
2       https://t.co/yjnio0p1jv flagstar bank disclose...
3       rwanda is set to host the headquarters of unit...
4       oops. i typed her name incorrectly (today’s br...
                              ...
1995    @jonikauf’s outfit goes crazy in lost kingdom ...
1996    this.\n\nlaws are not ethics. if a law is unet...
1997    @transportgovuk university of the west of engl...
1998    @usspacelawyer @garym03062 @commentary a witne...
1999    @matheuspereira everyone knows that you are a ...
Name: Text, Length: 2000, dtype: object

# **Removing punctuation marks**

---

In [ ]:
import string

punctuations=set(string.punctuation)
k=list(punctuations)
# print(k)
emp=[]
for i in features:
  emp1=""
  for j in i:
    if j not  in k:
      emp1+=j
  emp.append(emp1)

print(emp)
len(emp)
pd.set_option("display.max_colwidth",-1)

['charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination', 'badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh', 'httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity', 'rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda', 'oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz', 'it sucks for me since im focused on the nature aspect of things but the environmental problems we have all have their roots in social economic amp political issues simply recycling or using renewable energy is like fixing the top floor of a building with an unsteady foundation', 'enfont treballar a l’obra a partir dels 19 anys fins als 50 també q a partir dels 50 t’hagin jubilat degut a un accident laboral … crema mes q el “foc dels fogons” de qualsevol cuina sobreportantlavida', 'shawntarloff itsmieu you can also relate this to art too a lot of people are dismayed in starting art because of this kind of thing and i always try to tell them that everyone starts somewhere and those who are good by certain ages just trained enough to get there like with anything you learn', 'social security constant political crises distract the masses and they rob us blind meantime its coming at the american people with breathtaking speed amp every direction til people dont know where to look first its not an accident', 'filmthepolicela a broken rib can puncture a lung or lead to a collapsed lung  both much longer recoveries than just a break  get it checked', 'jacobringenwald akeithwatts countdankulatv i agree its a flawed response for a small  and many pl people i presume would agree that nuance amp understanding is needed in those cases\n\nbut its a good starting point  dont drink amp drive or dont play with guns is sound advice that sounds simplistic but nevertheless true', 'nzhksu telebusiness my question was rhetorical we all know russia is propping up their market and chinaindia are willing to pay inflated gas prices to further aid russia', 'wimbledon nick kyrgios admits spitting towards disrespectful spectator after beating paul jubb httpstcojkfqhimlqw good grief ‼️‼️ kyrgios is all class isn’t he… not', 'is booktwt a thing if so thats her and she speaks in perfect grammar and spellinc and punctuation and capitalization everyones favlrite moot httpstcookafyriuv8', 'saltburned when the first sign of surrender comes michael’s smile splits his face like a sharp knife through flesh it would chill dean to his very core if he were to witness this ice cold existence and its nature and the archangel would have an enjoyable time »', 'cofuckoff jespere que ça passera le plus vite possible ', 'roipaee joe98100959 formula1game redbullracing silverstoneuk i wrote to them nowwaiting for a responseive lost hope\nwith fifa games worked every year', '🤩 power back on 1855749  north vi in ladysmith near 1000 block 4th ave\ncause motor vehicle accident bchydro britishcolumbia canada poweroutage poweron', 'at the end we consume fictional stories to enjoy them so that seem fair personally i love seeing characters going trough their lowest as much as their highest so fucked up stuff doesnt spoil my enjoyment  though i did have few dreams about the last chapters httpstcopyx4a63c5u', 'duranto express a1 coach ac not working properly in 12294 prayagraj ltt passengers sweating\n\nfood for dinner unimpressive please improve standards irctcofficial \n\npeople wu think its rude2complain about services excuse\n\nnatgeotravel bbctravel railminindia westernrly', 'wterrence you poor man he couldnt care less about you', 'acroce66 by the way its never too late to tell the truth\nexcellent film the cast was incredible the tension well done and not melodramatic id say an 85 ', 'ew its almost valentine’s day httpstcofa5pv8i798', 'jakesucky abloop this is absolutely incredible just wow', 'people forget how good taysom is when hes used right', 'blackmercury3 i’m thinking that maybe ironwood told robyn about his plan to lure out watts but that raises a lot of questions about the specifics of her semblance', 'content creators  done is better than perfect  youtube presentation blog podcast video keynote speech influencer\n\nhttpstcomm3nzdktsa', 'its your fight to save the uk from the liars cheats amp charlatans steve bray crowdfunding fundrazr support and retweet\n\ndirect support for steves legal case\n httpstcorgjhx7hjcu', 'joycewhitevance thedemcoalition he answered clearly by invoking the 5th\n\nits a simple question especially for a member of the military  they swear to support and defend our constitution so anything other than a resounding yes is the same as saying hell no\n\nhe incriminated himself amp disgraced his uniform', 'zoidberg95 infinite diversity in infinite combinations means everybody who loves the trek watches the trek and helps create the trek or might someday do so is welcome star trek is as broad in scope and existence as the imaginations of everyone who has ever loved trek and it is good', 'imo trump is phuked let’s see if any republicans grow a spine after watching this 26 year old young woman show incredible courage doubtful 🙄', 'kbradjstorm bro katz is actually broken its ridiculous', 'johnbick1960 bobsouer i just listened to my first book read by ai—interesting  also suffers from the same problem  also pronounced “grimace” as “grimace” i could see ai readings for textbooks being useful', 'sad thing is hes causing more damage than trump because hes slightly brighter both are a serious threat to peace amp the environment crooks thinskinned amp utterly vindictive heading for a fall probably at the hands of their own acolytes  see ceausescu qadafi nero httpstcohm6csvzus3', 'accident in huntersville on nc73sam furr rd between mayes road and westmoreland rd traffic httpstcofwt2jwrevt', 'sausageroll jonasbusch7 alitaarmy just looking at the tweets in that trend she seems well insulated by sensible people  i almost freaked out but she’ll be ok', 'alitomorenoc no mames ya mejor lárgate del pri y deja de estar hundiendo más al partido y su militancia con pendejadas como esta\ncon esto que propones ahora si sería legal que el co esté armado hasta los dientes es la propuesta para una escalada armada sin sentido', 'innovation cybersecurity madeinfrance 👩\u200d💻 le pepr cybersecurite est lancé en france permettant des transferts de savoirs et technologiques entre industriels universités et grandes écoles 🕴️💻💶👉httpstcowtldk4jao8', 'ferrans53 probably is an xfl team', 'curry making 48m coming off a ring this mf living my dream😭😭😭😭 httpstcobn6n5fnpsz', 'bowtiedhandyman am sinple man…truck is tall truck is loud truck makes the bad thoughts in head go away for a while', 'realhfegelein dubbaewwteeeff peterdempsey92 aoc the reason europe can spend money on these low quality features is because we dont spend on defence and we dont spend on innovation which drives costs down all that comes from america', 'happiest birthday wishes goes to the one i could never replace the closest soul my whole heart to the one who has been always there for me the one that truly sfits the perfect half of me no words could ever be enough to show how much i love you💙 aeyaald', 'i got this email today and besties i feel like it’s going to be bad httpstcomfpuqdk4vl', 'soccergremio fez um ótimo 2012 era cotado pra ser titular em 2013 mas incrivelmente dps desse episódio com o lost por onde anda foi descartado pelo grêmio fidalgia eterna', 'beejoco izzzyzzzart bloommoonbeam ugh just realised reeling doesnt mean what i wanted to express 🙄 i meant like im excited over it xd', 'janeannee ive probably written and rewritten it in my head 50 times i want to get it right usually ill be in a mood and the words just flow so well  see 🤷\u200d♀️', 'writing a whole ass doc on all the problems in my school and possible solutions because the school hasn’t done anything to improve their issues at all if they won’t do it i might as well do', 'judiciarygop 1 first witness account\n2 under oath\n\nnice try though you ppl must be scared', 'and im excited as hell httpstcoprsidmywao', 'punta gorda  several antisemitic flyers have been reported seen in punta gorda according to local law enforcement httpstcon0veaubyjd', 'kpis to measure innovation\n impact on financial results\n engagement no of connected startups employees involved\n external visibilityreputation as an innovative company\n\nsuzano has been recently awarded among the top25 openinnovation challengers at global level mtbcss httpstco8qn7vtiunr', 'garykline itsjefftiedrich judiciarygop jimmy jordan a criminal defendant has no purpose being on a judiciary committee', 'joauwa anyainyodo aweberg citizennappa rprequelmemes again shit writing your information of the “about a year” between movies and timeline came in articles and interviews after the movie release after the backlash of a shitty storytelling  rey is a mook and is a future criminal for identity fraud', 'dream httpstcoyjmxomfqyl', 'denmark this is probably a better version httpstcoew090rh4lh', 'uhh are you lost you are too much a cutie to be following me oo the cuties are that way ➡️ httpstcox6n7ol47zy', 'isle of mora\n    area 61 sqkm\n    population 169\n    terrain cursed crumbling seamount\n    my mother once told me that even the first settlement here was younger than the windswept garden', 'pillowzac please take care of yourself and that brain of yours hangovers are notttt fun \n\nproud of you and the entire hyper team for pulling all of this together everyone cast and crew made this happen so cool to be here to witness it all unfold', 'voting will never solve sa’s problems…revolution is the answer', 'lcyclable gergerv une remise en question ne serait pas inutile pour le coup', 'realeubreak yardleyshooting hyrocarbonsrus to further inject some realism not shown here  \nputin invaded a sovereign countryukraineafter being frustrated by the silence amp inaction of the west regarding the breach of minsk agreement \natrocities commited against pro russian separatists by the ukraines nazi azov regiment httpstcorqan26rue2', 'trippydancer u a good person man and seems like almost fate for both you and whoever’s life you protected that you were there at the right time for them could potentially have been life changing for the both of you should respect yourself massively for it fr', 'davidedwards awww the poor baby let us tell you what religious persecution actually looks like marjorie my jewish brothers and sisters would like a word…', 'just learned today  not one of the 100 largest european companies were founded in the last 40 years the continent is dying  innovation creativity and risk are only found in america socialism has made europe an opportunity desert  no growth no hope', '🚨🌔 chelsea have made a contract offer to ousmane dembélé\n\nhis future will now be between barcelona or chelsea', 'ycmiycmiu bbcoq keithbaldrey you are confusing many issues the informed risk taken by investors worst ipo etc regarding the uk government picking up welfare riders and tax avoidance etc   if government chooses to use ridesharing this is an issue to address with them not the company same with taxation', 'maccabeus24 okay the flag burning is extreme but the democratic process doesnt work and is extremely flawed the voting system is crooked the rest of the world sees that', 'trustyourluck itsmeginob louisianadowns ntamm1215 best turf speed with a trainer winning at a 20 clip last 14 days', 'the objective of encouraging sc youth to engage in entrepreneurship rather than becoming jobseekers\n\n3rd call now open\nregister now at httpstcowshiqkaarj\n\nschedulecaste entrepreneurs startups innovation entrepreneurship technology venturecapital highereducation', 'cizruval zellsis ethoz best karambit in the game and vandal with best vfx and sfx in the game', 'and there are times where every celebrity feels like they dont want cameras screams and crowds so please please dont give hate towards him he did waved army and the reporters and even apologized on weverse eventho he doesnt supposed too taehyung did nothing wrong so stop', 'ashokgehlot51 sir these two people should be punished not by indian lawbut in the same way islamic countries punish thempublic execution no mercy should be allowed no legal options should be given indian law only give shelter to such people', 'realme gt neo2 june 2022 update adds more omoji decoration item improve street mode and many more httpstcor9iygzxzou', 'always ask yourself the questions when the right attacks the testimony given under oathwhy havent they give  any when all the people are trump are talkingwho is left that says otherwise he is running out of people willing to lie january6thcommitteehearings', 'what is wrong with y’all… httpstcotyyxkdc9l6', 'no winner of the €176m euromillions jackpot my plans disappear once again into the gulag of dreams', 'fostering clean energy innovationfinancial advisor explains how to topspeed car httpstcoguyylibymk httpstco2j0ewzt9b4', 'davidmacdougall the text says nothing about finland or sweden amending their national legislation in connection with turkey or at its behest it simply refers to existing law and current legislative processes why the disinformation nato turkki', 'ieee in collaboration with ieee tems and global innovation amp entrepreneurship company announced the launch of the arab iot amp ai challenge in 11 arab countries\nieee iot ai arab arabiot arabiotaichallenge technology\nhttpstcoz9jvdby5kl', 'the future cbdc exchange settlement takes place on lcx with the interoperability provided by qnt and overledger httpstco7uf9fy3upv', 'climate change needs more innovation we must be pro active every day  thanks c mck for doing good work httpstcouwbmpzv06e', 'swearyexpat jamesturner37 marilynstowe blazingplectrum will you behave i’m sure your blasphemy is almost equally to blame for this', 'what are the term lengths for loan guarantees direct loans and bridge financing provided to poverty reduction projects\n\ntypically term lengths are 5 or 10 years but we are happy to work with you to discuss what might work best for you and your organization httpstcoq9hxcfgrrw', 'how are you a bad boy drinking barefoot bubbly badboysclub zuesnetwork', 'vivekch46672161 hi\nhow are you friend our machine met with an accident today now how do we you know if the head of the machine is in the right angle', 'tennessee to receive 5 million in settlement with pharmaceutical company httpstcoazo28z4nk0', 'problematicpj reuters the majority of people are concerned with the here and now because people are suffering here and now  that clown show is pointless they already announced there will be no criminal referrals', 'texasguard looks like an admission of criminal activity against one of yours httpstcor5ti3ouc4b', 'tpostmillennial she keeps it up that will turn into another 22m settlement🤣😂', 'scheduling tweets for the trending party with a bandaged wrist 😂 it has taken me infinitely longer than if both were functional but thats okay and yes i will probably get my wrist looked at by a doctor soon to be safe i keep straining it lifting my comforter at night 😬', 'goodbydays え？ガチですか？？\n足引っ張る気しかしませんよ😹😹', 'masekothembaj imigodoyi are those who are failing  eskom now they took the jobs with the intention of fixing what was perceived as broken but after 3years nothing is showing as a sign of fixing', 'rcderbyandnotts fleetwoodmac rockchoir ‘sara’ love stevie nicks’ voice but all there songs are great 😀🎶 i was 7 so probably climbing the big apple tree at the bottom of the garden 😂', 'trumpery45 concodanomics usdc is just a centralized intermediary operating to top of secure transparent blockchain of course you can pay with your visa working on top of usdc for settlement', 'scuderiaferrari f1 lewishamilton mercedesamgf1 why is it so hard to give the name of a white criminal', 'aawsatnews nasa it is possible to hit any asteroid approaching the earth with nuclear missiles to destroy or change course', 'rafluton problem is foxes will only go and dig it up… foxbats', '9newsaus having all 3 flags together waving sidebyside is a more positive and forwardlooking message imo \n\nso as to say the aborigine the torres strait islander amp all those who presence is the result of british settlement  we’re trying to build a future in which we’re all united', 'hudsrob i wouldnt touch him with 10 pole man not worth the risk i hope we sign edwards andor lundy', 'mskatz jewishstudies a huge welcome to melinda and mary we will miss you so much michelle thank you for all the amazing work you have done dulls the pain of your departure knowing you will be such an incredible rabbi 💜✡️💜', 'judiciarygop bad legal take  statements against interest such as\n we are going to get charged with every crime imaginable  \n\nare specifically defined as not hearsay  \n\nthis is what happens when a gym teachersexual abuse enabler tries to argue the law jimjordan httpstcocet75lsavo', 'listen to her words\n\nthis woman just testified that trump didnt just reach for but grabbed the steering wheel\n\nfrom the back seat\n\nwhile it was moving\n\nwho is stupid enough to believe this\n\noh wait i guess we know the answer to that question 😂😂😂 httpstco8vpz410ysy', 'without mechanisms to understand give credit to and share best practice that works how do we continue to improve what we do you need reasons for people to value edi  you move beyond tick box when edi comes to life in practice 2', 'the people have spoken and the people are wrong httpstcokpgopde6ab', 'brianstelter ive never seen a truer damn i backed the wrong horse  face', 'should someone tell trump that witness tampering is a crime what about assault of a police officer 😳🤯trump january6thcommitteehearings january6thcommiteehearings', 'thetastyworks tastytrade lizjny how about a dntt trade in googl  sell the jan31st 14001425144751450 jade lizard for 520 downside risk around 1420 if necessary dont mind entering earnings week long at 1420', 'shortlatinablm adriennw govmlg im saying that you can still use abortion as a form of birth control because of the state you live in so you can continue to make poor choice and not have to worry about it', 'tiwindisch jfahr i wouldn’t care about tampering had the bucks not gotten screwed by the league on the bogdanovich deal much easier to swallow since they won the championship of course same rules should apply to everyone', 'poor charlie 😭😭😂😂😂', 'briantylercohen isnt that assaulting an officer of the law', 'what do capex\xa0projects and baseball have in common discover how to manage risk and optimize your projects by reading about baseball read more  httpstcovqwbmqpvid  unifiedprojectexecution httpstcoxscsrizswd', 'me why do i keep tasting blood when i cough\nme rinses out mouth\nme ahh thats probably why', 'jlcjane govtimwalz not hiding behind her that’s what she said i have different feelings i think everyone is be capable of making those decisions my wife is just a standard liberal which is judgy and a bit ignorant here’s the data httpstcosaj3ryieho  i was wrong on the year sorry', 'how circularity transformation is impacting supply chain innovation httpstcokmvphppyl6', 'yep but thats also kinda cus expressing myself is hard for me it’s a little easier in english than in my mother tongue for some reason httpstcoyi6s9j326j', 'i dont know if there will be lunch maybe ieeveleen has a clue httpstcoymm9xawpth', 'does the supreme court really believe in the rul

<ipython-input-8-6284b5e8f0b3>:16: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option("display.max_colwidth",-1)

In [ ]:
df_["Tweets_w/o_punctuations"]=emp

In [ ]:
df_

,Text,Language,Label,Tweets_w/o_punctuations
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz
...,...,...,...,...
1995,@JoniKauf’s outfit goes crazy in Lost Kingdom https://t.co/rn9IdIOJwC,en,negative,jonikauf’s outfit goes crazy in lost kingdom httpstcorn9idiojwc
1996,"THIS.\n\nLaws are NOT ethics. If a law is unethical you can make the choice to act ethically, even if it is a huge risk to you and/or your career. You can choose to protect people, and do the right thing.\n\nYeah, it's scary, but sometimes the right thing is scary. https://t.co/QJ69IDpjBI",en,litigious,this\n\nlaws are not ethics if a law is unethical you can make the choice to act ethically even if it is a huge risk to you andor your career you can choose to protect people and do the right thing\n\nyeah its scary but sometimes the right thing is scary httpstcoqj69idpjbi
1997,"@transportgovuk university of the West of England frenchay Bristol , the one way system is in breach of the highway code, buses often try to drive into me expecting me to give way to them when they're on my left, something needs to be done so buses are on the right https://t.co/qQc1PPcNx6",en,litigious,transportgovuk university of the west of england frenchay bristol the one way system is in breach of the highway code buses often try to drive into me expecting me to give way to them when theyre on my left something needs to be done so buses are on the right httpstcoqqc1ppcnx6
1998,"@USSpaceLawyer @GaryM03062 @Commentary A witness repeating what a non-testifying declarant told her for the purpose of proving the truth of the declarant's statement (i.e., things Trump allegedly did) is most definitely hearsay.",en,litigious,usspacelawyer garym03062 commentary a witness repeating what a nontestifying declarant told her for the purpose of proving the truth of the declarants statement ie things trump allegedly did is most definitely hearsay
1999,@MatheusPereira Everyone knows that you are a deceiver.. Everyone knows that you are a failure.. Everyone knows that you only want the value of the contract.. Without doing anything on the field.. You are a disgrace to the ball.,en,litigious,matheuspereira everyone knows that you are a deceiver everyone knows that you are a failure everyone knows that you only want the value of the contract without doing anything on the field you are a disgrace to the ball

# **Removing stopwords**

In [ ]:
import nltk
nltk.download()

# DWONLOAD-->stopwords-->QUIT

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader>

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader>

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> stopwords

    Downloading package stopwords to /root/nltk_data...
      Unzipping corpora/stopwords.zip.

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

True

In [ ]:
import nltk
from nltk.corpus import stopwords
df_li=[]
sent_li=[]
for sent in df_["Tweets_w/o_punctuations"]:
  words_li=[]
  for word in sent.split():
    if word not in stopwords.words('english'):
      words_li.append(word)
  sent_li.append(" ".join(words_li))

In [ ]:
df_['Tweets_w/o_stopwords']=pd.Series(sent_li,index=df_.index)

In [ ]:
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz

# **Removing all the links**

import re


emp_list=[]


for i in df_["Tweets_w/o_stopwords"]:


  new_text=re.sub(r"\b" + "https" + r"\w+", "", i)


  emp_list.append(new_text)


df_["Tweets_w/o_links"]=emp_list


df_.head()

---

In this way also the code can be written

In [ ]:
import re
df_["Tweets_w/o_links"]=df_["Tweets_w/o_stopwords"].map(lambda i:re.sub(r"\b" + "https" + r"\w+", "", i))
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th

# **Tokenization**

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
token=[i.split() for i in df_["Tweets_w/o_links"]]
df_["token"]=token
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links,token
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,"[charliecorley, kristine1g, amyklobuchar, stylewriternyc, testimony, evidence, court, law, state, federal, must, stand, cross, examination]"
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja,"[badbunny, como, dos, gotas, de, agua, joven, se, disfraza, de, bad, bunny, causa, tumulto, en, alfombra, roja]"
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity,"[flagstar, bank, discloses, data, breach, impacted, 15, million, individuals, cybersecurity]"
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda,"[rwanda, set, host, headquarters, united, nations, development, programme’s, undp, new, innovation, financing, facility, find, sovereigngroup, sovereignafrica, undp, rwanda]"
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th,"[oops, typed, name, incorrectly, today’s, brave, witness, cassidyhutchinson, 6, premeditatedviolence, 7, probaby, witnesstamperig, don’t, forget, markmeadows, requesting, pardon, trumpknew, trumpcapitolcoupattack, capitolcoupattempt, neverforgetjanuary6th, neverforgetjan6th]"

# **Lemmatization**

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [ ]:
import nltk
nltk.download()

#Download-->wordnet-->quit

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> wordnet

    Downloading package wordnet to /root/nltk_data...

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

True

In [ ]:
list2=df_["token"].map(nltk.pos_tag)
list2

0       [(charliecorley, NN), (kristine1g, NN), (amyklobuchar, NN), (stylewriternyc, NN), (testimony, NN), (evidence, NN), (court, NN), (law, NN), (state, NN), (federal, JJ), (must, MD), (stand, VB), (cross, NN), (examination, NN)]
1       [(badbunny, NN), (como, NN), (dos, JJ), (gotas, NN), (de, IN), (agua, FW), (joven, FW), (se, FW), (disfraza, FW), (de, FW), (bad, JJ), (bunny, NN), (causa, NN), (tumulto, NN), (en, IN), (alfombra, NN), (roja, NN)]
2       [(flagstar, NN), (bank, NN), (discloses, VBZ), (data, NNS), (breach, NN), (impacted, VBD), (15, CD), (million, CD), (individuals, NNS), (cybersecurity, NN)]
3       [(rwanda, NN), (set, VBN), (host, NN), (headquarters, NN), (united, JJ), (nations, NNS), (development, NN), (programme’s, NN), (undp, JJ), (new, JJ), (innovation, NN), (financing, NN), (facility, NN), (find, VBP), (sovereigngroup, NN), (sovereignafrica, NN), (undp, JJ), (rwanda, NN)]
4       [(oops, NNS), (typed, VBD), (name, NN), (incorrectly, RB), (today’s, VBZ), (brave, JJ), (witness, NN), (cassidyhutchinson, NN), (6, CD), (premeditatedviolence, NN), (7, CD), (probaby, NN), (witnesstamperig, NN), (don’t, NN), (forget, NN), (markmeadows, VBZ), (requesting, VBG), (pardon, VB), (trumpknew, JJ), (trumpcapitolcoupattack, NN), (capitolcoupattempt, NN), (neverforgetjanuary6th, NN), (neverforgetjan6th, NN)]
                                                                                                                                                                                                                       ...
1995    [(jonikauf’s, NN), (outfit, NN), (goes, VBZ), (crazy, JJ), (lost, VBN), (kingdom, NN)]
1996    [(laws, NNS), (ethics, NNS), (law, NN), (unethical, JJ), (make, NN), (choice, NN), (act, NN), (ethically, RB), (even, RB), (huge, JJ), (risk, NN), (andor, NNS), (career, VBP), (choose, JJ), (protect, JJ), (people, NNS), (right, JJ), (thing, NN), (yeah, RB), (scary, JJ), (sometimes, RB), (right, JJ), (thing, NN), (scary, JJ)]
1997    [(transportgovuk, NN), (university, NN), (west, JJS), (england, NN), (frenchay, NN), (bristol, VBD), (one, CD), (way, NN), (system, NN), (breach, VBP), (highway, NN), (code, NN), (buses, NNS), (often, RB), (try, VBP), (drive, JJ), (expecting, VBG), (give, JJ), (way, NN), (theyre, NN), (left, VBD), (something, NN), (needs, NNS), (done, VBN), (buses, NNS), (right, RB)]
1998    [(usspacelawyer, JJ), (garym03062, NN), (commentary, JJ), (witness, NN), (repeating, VBG), (nontestifying, VBG), (declarant, JJ), (told, VBD), (purpose, JJ), (proving, VBG), (truth, NN), (declarants, NNS), (statement, NN), (ie, JJ), (things, NNS), (trump, VBP), (allegedly, RB), (definitely, RB), (hearsay, VB)]
1999    [(matheuspereira, NN), (everyone, NN), (knows, VBZ), (deceiver, RP), (everyone, NN), (knows, VBZ), (failure, NN), (everyone, NN), (knows, VBZ), (want, VBP), (value, NN), (contract, NN), (without, IN), (anything, NN), (field, NN), (disgrace, NN), (ball, NN)]
Name: token, Length: 2000, dtype: object

In [ ]:
from nltk.text import TokenSearcher
from nltk.sem.logic import Tokens
from nltk.corpus import wordnet

def get_wordnet_pos(i):
  # for i in my_dict.values():
    if i.startswith('J'):
        return wordnet.ADJ
    elif i.startswith('V'):
        return wordnet.VERB
    elif i.startswith('N'):
        return wordnet.NOUN
    elif i.startswith('R'):
        return wordnet.ADV
    else:
        return ''

In [ ]:
lem=list(map(lambda x: {i:get_wordnet_pos(j) for i,j in x },list2))
lem

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [ ]:
lemmatizer = WordNetLemmatizer()
list33=[]
for i in lem:
  list3=[]
  for k,v in i.items():
    if v=='':
      v='n'
    lemmatized_words=lemmatizer.lemmatize(k, pos=v)
    list3.append(lemmatized_words)
  list33.append(" ".join(list3))
# print(list33)

In [ ]:
df_["Lemmatized_sentences"]=list33
df_

# **Count Vectorization**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links,token,Lemmatized_sentences
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,"[charliecorley, kristine1g, amyklobuchar, stylewriternyc, testimony, evidence, court, law, state, federal, must, stand, cross, examination]",charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja,"[badbunny, como, dos, gotas, de, agua, joven, se, disfraza, de, bad, bunny, causa, tumulto, en, alfombra, roja]",badbunny como dos gotas de agua joven se disfraza bad bunny causa tumulto en alfombra roja
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity,"[flagstar, bank, discloses, data, breach, impacted, 15, million, individuals, cybersecurity]",flagstar bank disclose data breach impact 15 million individual cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda,"[rwanda, set, host, headquarters, united, nations, development, programme’s, undp, new, innovation, financing, facility, find, sovereigngroup, sovereignafrica, undp, rwanda]",rwanda set host headquarters united nation development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th,"[oops, typed, name, incorrectly, today’s, brave, witness, cassidyhutchinson, 6, premeditatedviolence, 7, probaby, witnesstamperig, don’t, forget, markmeadows, requesting, pardon, trumpknew, trumpcapitolcoupattack, capitolcoupattempt, neverforgetjanuary6th, neverforgetjan6th]",oops type name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows request pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_["Lemmatized_sentences"], df_["Label"],random_state=0)

In [ ]:
vect_train = vectorizer.fit_transform(X_train).toarray()
vect_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vocab_dict = vectorizer.vocabulary_.copy()
dict(sorted(vocab_dict.items(), key=lambda item: item[1]))

In [ ]:
vect_test = vectorizer.transform(X_test).toarray()
vect_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:

from sklearn.svm import SVC

In [ ]:
labels.unique()

array(['litigious', 'negative', 'positive', 'uncertainty'], dtype=object)

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
nb.score(vect_train, y_train),nb.score(vect_test, y_test)

(0.988, 0.44)

In [ ]:
vect_test, y_test

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 405     litigious
 1190    positive
 1132    uncertainty
 731     negative
 1754    uncertainty
            ...
 936     uncertainty
 1524    negative
 1415    negative
 1223    negative
 1548    uncertainty
 Name: Label, Length: 500, dtype: object)

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
naive_train=nb.score(vect_train, y_train)
naive_test=nb.score(vect_test, y_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(vect_train,y_train)
knn_train=knn.score(vect_train, y_train)
knn_test=knn.score(vect_test, y_test)

In [ ]:


svm = SVC(C=1.0,kernel="rbf")
svm.fit(vect_train,y_train)
svm_train=svm.score(vect_train, y_train)
svm_test=svm.score(vect_test, y_test)

In [ ]:
# import pandas as pd/

In [ ]:
Scores={"KNN":[knn_train,knn_test],
        "SVM":[svm_train,svm_test],
        "Naive Bayes":[naive_train,naive_test]}

row=["Train Score","Test Score"]

df_score=pd.DataFrame(Scores,index=row)

In [ ]:
df_score

               KNN       SVM  Naive Bayes
Train Score  0.748  0.998667  0.988
Test Score   0.590  0.930000  0.440

In [ ]:
def lower_str(sentences):
  if type(sentences)!=str :
    sentences=sentences.astype(str)
  sentences=sentences.lower()
  return sentences

sentence="I AM so happy since i have completed my dATA SCience course from https://aiadventures.com.google . Now i will start with my machine learning course soon"
out1=lower_str(sentence)

In [ ]:
out1

'i am so happy since i have completed my data science course from https://aiadventures.com.google . now i will start with my machine learning course soon'

In [ ]:
import string
def punc(x):
  punctuations=set(string.punctuation)
  k=list(punctuations)
  emp=[]
  emp1=""
  for j in x:
    if j not  in k:
      emp1+=j
  emp.append(emp1)
  return emp

out2=punc(out1)

In [ ]:
out2

['i am so happy since i have completed my data science course from httpsaiadventurescomgoogle  now i will start with my machine learning course soon']

In [ ]:
# import nltk
# from nltk.corpus import stopwords
# stopwords.words("english")

In [ ]:
# import nltk
# nltk.download()
# # DWONLOAD-->stopwords-->QUIT
# import nltk
# from nltk.corpus import stopwords
# import nltk
# from nltk.corpus import stopwords
# stopwords.words("english")

def stopwords_(y):
  df_li=[]
  sent_li=[]
  words_li=[]
  for i in y:
    for word in i.split():
      if word not in stopwords.words('english'):
        words_li.append(word)
    sent_li.append(" ".join(words_li))
    return sent_li

out3=stopwords_(out2)

In [ ]:
out3

['happy since completed data science course httpsaiadventurescomgoogle start machine learning course soon']

In [ ]:
import re
def links(z):
  for i in z:

    z1=re.sub(r"\b" + "https" + r"\w+", "", i)
    return z1

out4=links(out3)

In [ ]:
out4

'happy since completed data science course  start machine learning course soon'

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
def token(z):
  token=z.split()

  return token

out5=token(out4)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
out5

['happy',
 'since',
 'completed',
 'data',
 'science',
 'course',
 'start',
 'machine',
 'learning',
 'course',
 'soon']

In [ ]:
def lemmatization_of_testds(k):
  s=nltk.pos_tag(k)
  return s
out6=lemmatization_of_testds(out5)

In [ ]:
out6

[('happy', 'JJ'),
 ('since', 'IN'),
 ('completed', 'VBN'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('course', 'NN'),
 ('start', 'NN'),
 ('machine', 'NN'),
 ('learning', 'VBG'),
 ('course', 'NN'),
 ('soon', 'RB')]

In [ ]:
def lem_1(i):
    if i.startswith('J'):
        return wordnet.ADJ
    elif i.startswith('V'):
        return wordnet.VERB
    elif i.startswith('N'):
        return wordnet.NOUN
    elif i.startswith('R'):
        return wordnet.ADV
    else:
        return ''

In [ ]:
lem=list(map(lambda x: {i:lem_1(j) for i,j in out6 },out6))
lem

In [ ]:
def lem_2(lem):

  lemmatizer = WordNetLemmatizer()
  list33=[]
  # print(lem)
  dictionary = {key: value for key, value in lem}
  # print(dictionary)
  list3=[]
  for k,v in dictionary.items():
    print(k,v,lem_1(v))
    if lem_1(v)=='':
      v='n'
    else:
      v=lem_1(v)
    lemmatized_words=lemmatizer.lemmatize(k, pos=v)
    list3.append(lemmatized_words)
  list33.append(" ".join(list3))
  return list33

out8=lem_2(out6)

happy JJ a
since IN
completed VBN v
data NNS n
science NN n
course NN n
start NN n
machine NN n
learning VBG v
soon RB r

In [ ]:
out8

['happy since complete data science course start machine learn soon']

In [ ]:
vect_test = vectorizer.transform(out8).toarray()
vect_test

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
predict=nb.predict(vect_train)

In [ ]:
actual=y_train

In [ ]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(actual,predict)
cm

array([[313,   0,   0,   0],
       [  3, 401,   0,   7],
       [  0,   2, 447,   6],
       [  0,   0,   0, 321]])

In [ ]:
tn,fp,fn,tp=cm#.ravel()

In [ ]:
tn,fp,fn,tp

(array([313,   0,   0,   0]),
 array([  3, 401,   0,   7]),
 array([  0,   2, 447,   6]),
 array([  0,   0,   0, 321]))

In [ ]:
precision = tp / (tp + fp)
precision

<ipython-input-315-14cf9d9238e4>:1: RuntimeWarning: invalid value encountered in true_divide
  precision = tp / (tp + fp)

array([0.        , 0.        ,        nan, 0.97865854])

In [ ]:
recall = tp / (tp + fn)
recall

<ipython-input-316-b8afcec01478>:1: RuntimeWarning: invalid value encountered in true_divide
  recall = tp / (tp + fn)

array([       nan, 0.        , 0.        , 0.98165138])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
 print(classification_report(actual, predict))

              precision    recall  f1-score   support

   litigious       0.99      1.00      1.00       313
    negative       1.00      0.98      0.99       411
    positive       1.00      0.98      0.99       455
 uncertainty       0.96      1.00      0.98       321

    accuracy                           0.99      1500
   macro avg       0.99      0.99      0.99      1500
weighted avg       0.99      0.99      0.99      1500

In [ ]:
df_score

               KNN       SVM  Naive Bayes
Train Score  0.748  0.998667  0.988
Test Score   0.590  0.930000  0.440